resources:
  repositories:
    - repository: template
      type: git
      name: 'Templates/Template'
      ref: v2
      
trigger: none
schedules:
- cron: '0 1 * * SUN'
  displayName: Weekly Next Minor build
  branches:
    include:
    - master
  always: true

variables:
- group: secrets
      
stages:
- stage: Build
  jobs:
  - job: Build
    variables:
      build.clean: all
      platform: x64
      version: "nextminor"
      appVersion: "1.0"
      appBuild: $(Build.BuildID)
      appRevision: 0
      createRuntimePackages: False
      skipComponentGovernanceDetection: True

    pool:
      name: Default

    steps:
    - template: build-steps.yml@template
