resources:
  repositories:
    - repository: template
      type: git
      name: 'Templates/Template'
      ref: v2
      
trigger: none

variables:
- group: secrets
      
stages:
- stage: Build
  jobs:
  - job: Build
    variables:
      build.clean: all
      platform: x64
      version: "current"
      appVersion: '1.0'
      appBuild: $(Build.BuildID)
      appRevision: 0
      createRuntimePackages: False
      skipComponentGovernanceDetection: True

    pool:
      name: Release

    steps:
    - template: build-steps.yml@template


